### PR TITLE
feat: discord frame rendering

### PR DESCRIPTION
**Pull request by michalkvasnicak**

### CODE REVIEW

**Comment by stephancill** [comment]
Struggling to get it working locally. Query selector seems to not select the frame nodes and getting this error 
Screenshot 2024-07-04 at 16 49 04

perhaps a background script messaging issue?

**Comment by michalkvasnicak** [comment]
@stephancill I don't have any issues at all.

image

**Comment by michalkvasnicak** [comment]
@stephancill it seems like some problem on your side, probably network issue or something like that because it weren't able to resolve the URL.

**Review by stephancill — APPROVED** [review]
lgtm!

**Pull request merged**
